ALTER TABLE users
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'BUYER';

ALTER TABLE users
    ADD COLUMN seller_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE products
    ADD COLUMN seller_id BIGINT;
ALTER TABLE products
    ADD COLUMN stock_quantity INTEGER NOT NULL DEFAULT 0;

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_complaints_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_complaints_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_products_seller_id ON products (seller_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_reviews_product_id ON reviews (product_id);
CREATE INDEX idx_complaints_status ON complaints (status);
