CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO roles (name)
SELECT 'BUYER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'BUYER');

INSERT INTO roles (name)
SELECT 'SELLER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'SELLER');

INSERT INTO roles (name)
SELECT 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id BIGINT;

UPDATE users
SET role_id = (SELECT id FROM roles WHERE name = 'BUYER')
WHERE role_id IS NULL;

UPDATE users
SET role_id = (SELECT id FROM roles WHERE name = 'SELLER')
WHERE LOWER(email) = 'seller@graminehaat.com';

UPDATE users
SET role_id = (SELECT id FROM roles WHERE name = 'ADMIN')
WHERE LOWER(email) = 'admin@graminehaat.com';

UPDATE users
SET role_id = (SELECT id FROM roles WHERE name = 'BUYER')
WHERE role_id IS NULL;
