spring.application.name=backend
server.port=8080

# Database Configuration (H2 In-Memory for fast development)
spring.datasource.url=jdbc:h2:mem:haatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initial Data Load
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
